# Generated by Django 5.2.4 on 2025-07-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteMiningPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform_logos/')),
                ('point_of_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('point_of_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('point_of_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('energy_price', models.DecimalField(blank=True, decimal_places=4, help_text='Energy price in $/kWh', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remote Mining Platform',
                'verbose_name_plural': 'Remote Mining Platforms',
                'ordering': ['name'],
            },
        ),
    ]
