# Generated by Django 5.2.4 on 2025-07-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0005_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Bitcoin Price in USD', max_digits=12, null=True)),
                ('network_hashrate_ehs', models.DecimalField(blank=True, decimal_places=3, help_text='Network Hashrate in EH/s', max_digits=15, null=True)),
                ('network_difficulty', models.BigIntegerField(blank=True, help_text='Network Difficulty', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Data',
                'verbose_name_plural': 'API Data',
            },
        ),
    ]
