# Generated by Django 5.2.4 on 2025-07-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0010_settings_dark_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='developer_mode',
            field=models.BooleanField(default=False, help_text='Enable developer mode to show database IDs'),
        ),
    ]
