# Generated by Django 5.2.4 on 2025-07-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0013_settings_pool_fee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='block_reward',
            field=models.DecimalField(decimal_places=8, default=3.125, help_text='Bitcoin block reward (BTC per block)', max_digits=10),
        ),
    ]
