# Generated by Django 5.2.4 on 2025-07-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0015_payout_closing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='value_at_payout',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD value at payout (payout_amount * closing_price)', max_digits=15, null=True),
        ),
    ]
