# Generated by Django 5.2.4 on 2025-07-21 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0016_payout_value_at_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(help_text='Date of the expense')),
                ('category', models.CharField(choices=[('CAPEX', 'CAPEX'), ('OPEX', 'OPEX')], help_text='Expense category', max_length=10)),
                ('description', models.CharField(help_text='Short description of the expense', max_length=200)),
                ('expense_amount', models.DecimalField(decimal_places=2, help_text='Expense amount in USD', max_digits=12)),
                ('invoice_link', models.URLField(blank=True, help_text='Link to invoice document', null=True)),
                ('receipt_link', models.URLField(blank=True, help_text='Link to receipt document', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='mining.remoteminingplatform')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date'],
            },
        ),
    ]
