# Generated by Django 5.2.4 on 2025-07-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0017_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, help_text='Short description of the expense', max_length=200, null=True),
        ),
    ]
