# Generated by Django 5.2.4 on 2026-02-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0022_miner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='closing_price_fetched_at',
            field=models.DateField(blank=True, help_text='Date when closing price was last fetched from API', null=True),
        ),
    ]
