# Generated by Django 5.2.4 on 2026-03-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0023_payout_closing_price_fetched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('CAPEX', 'CAPEX'), ('OPEX', 'OPEX')], db_index=True, help_text='Expense category', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(db_index=True, help_text='Date of the expense'),
        ),
        migrations.AlterField(
            model_name='miner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this miner is currently turned on. Only affects the Forecasting Dashboard.'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_date',
            field=models.DateField(db_index=True, help_text='Date of the payout'),
        ),
    ]
