# Generated by Django 5.2.4 on 2025-07-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteminingplatform',
            name='point_of_contact_telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
