# Generated by Django 5.2.4 on 2025-07-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_remoteminingplatform_point_of_contact_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteminingplatform',
            name='portal_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
