# Generated by Django 5.2.4 on 2025-07-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0004_miner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinmarketcap_api_key', models.CharField(blank=True, help_text='CoinMarketCap API Key', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
