# Generated by Django 5.2.4 on 2025-07-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0007_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Bitcoin transaction ID', max_length=100, null=True),
        ),
    ]
