# Generated by Django 5.2.4 on 2025-07-15 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0008_alter_payout_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='mining.remoteminingplatform'),
        ),
    ]
