# Generated by Django 5.2.4 on 2025-07-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0009_payout_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Enable dark mode theme'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='coinmarketcap_api_key',
            field=models.CharField(blank=True, help_text='CoinMarketCap API Key for Bitcoin price data', max_length=255, null=True),
        ),
    ]
