# Generated by Django 5.2.4 on 2025-07-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0011_settings_developer_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='avg_block_fees_24h',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='24h Average Block Fees in BTC', max_digits=12, null=True),
        ),
    ]
