# Generated by Django 5.2.4 on 2025-07-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0003_remoteminingplatform_portal_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='miner_images/')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('product_link', models.URLField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('platform_internal_id', models.CharField(blank=True, help_text='Internal platform ID', max_length=100, null=True)),
                ('hashrate', models.DecimalField(blank=True, decimal_places=3, help_text='TH/s', max_digits=10, null=True)),
                ('power', models.DecimalField(blank=True, decimal_places=3, help_text='kW', max_digits=8, null=True)),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, help_text='W/TH', max_digits=8, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='USD', max_digits=12, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miners', to='mining.remoteminingplatform')),
            ],
        ),
    ]
