# Generated by Django 5.2.4 on 2025-07-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0006_apidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_date', models.DateField(help_text='Date of the payout')),
                ('payout_amount', models.DecimalField(decimal_places=8, help_text='Payout amount in BTC', max_digits=12)),
                ('transaction_id', models.CharField(help_text='Bitcoin transaction ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'ordering': ['-payout_date'],
            },
        ),
    ]
