# Generated by Django 5.2.4 on 2025-07-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0012_apidata_avg_block_fees_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='pool_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Pool fee percentage (e.g. 2.5 for 2.5%)', max_digits=5),
        ),
    ]
