# Generated by Django 5.2.4 on 2025-07-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0014_settings_block_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='closing_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bitcoin closing price in USD at payout date', max_digits=12, null=True),
        ),
    ]
