# Generated by Django 5.2.4 on 2025-07-21 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0018_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='mining.remoteminingplatform'),
            preserve_default=False,
        ),
    ]
