# Generated by Django 5.2.4 on 2025-07-22 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0020_alter_expense_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topup_date', models.DateField(help_text='Date of the top-up')),
                ('topup_amount', models.DecimalField(decimal_places=2, help_text='Top-up amount in USD', max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Description of the top-up', null=True)),
                ('receipt_link', models.URLField(blank=True, help_text='Link to receipt document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='mining.remoteminingplatform')),
            ],
            options={
                'verbose_name': 'Top-Up',
                'verbose_name_plural': 'Top-Ups',
                'ordering': ['-topup_date'],
            },
        ),
    ]
