# Generated by Django 5.2.4 on 2026-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0021_topup'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this miner is currently turned on. Only affects the Forecasting Dashboard.'),
        ),
    ]
