# Generated by Django 5.2.4 on 2026-03-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0024_add_db_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miner',
            options={'ordering': ['model']},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='coinmarketcap_api_key',
        ),
    ]
