# Generated by Django 5.2.4 on 2026-03-24 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0025_remove_coinmarketcap_api_key_from_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='dark_mode',
        ),
    ]
